/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as CausaAnimalRouteImport } from './routes/causa-animal'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as MedicamentosRouteImport } from './routes/medicamentos'
import { Route as OcorrenciaRouteImport } from './routes/ocorrencia'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as ServicosRouteImport } from './routes/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CausaAnimalRoute = CausaAnimalRouteImport.update({
  id: '/causa-animal',
  path: '/causa-animal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentosRoute = MedicamentosRouteImport.update({
  id: '/medicamentos',
  path: '/medicamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciaRoute = OcorrenciaRouteImport.update({
  id: '/ocorrencia',
  path: '/ocorrencia',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/causa-animal': typeof CausaAnimalRoute
  '/comunidade': typeof ComunidadeRoute
  '/gestao': typeof GestaoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/ocorrencia': typeof OcorrenciaRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/causa-animal': typeof CausaAnimalRoute
  '/comunidade': typeof ComunidadeRoute
  '/gestao': typeof GestaoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/ocorrencia': typeof OcorrenciaRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/atendimento': typeof AtendimentoRoute
  '/causa-animal': typeof CausaAnimalRoute
  '/comunidade': typeof ComunidadeRoute
  '/gestao': typeof GestaoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/ocorrencia': typeof OcorrenciaRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/saude': typeof SaudeRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/atendimento'
    | '/causa-animal'
    | '/comunidade'
    | '/gestao'
    | '/medicamentos'
    | '/ocorrencia'
    | '/perfil'
    | '/registro'
    | '/saude'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/atendimento'
    | '/causa-animal'
    | '/comunidade'
    | '/gestao'
    | '/medicamentos'
    | '/ocorrencia'
    | '/perfil'
    | '/registro'
    | '/saude'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/atendimento'
    | '/causa-animal'
    | '/comunidade'
    | '/gestao'
    | '/medicamentos'
    | '/ocorrencia'
    | '/perfil'
    | '/registro'
    | '/saude'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AtendimentoRoute: typeof AtendimentoRoute
  CausaAnimalRoute: typeof CausaAnimalRoute
  ComunidadeRoute: typeof ComunidadeRoute
  GestaoRoute: typeof GestaoRoute
  MedicamentosRoute: typeof MedicamentosRoute
  OcorrenciaRoute: typeof OcorrenciaRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  SaudeRoute: typeof SaudeRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causa-animal': {
      id: '/causa-animal'
      path: '/causa-animal'
      fullPath: '/causa-animal'
      preLoaderRoute: typeof CausaAnimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamentos': {
      id: '/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof MedicamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencia': {
      id: '/ocorrencia'
      path: '/ocorrencia'
      fullPath: '/ocorrencia'
      preLoaderRoute: typeof OcorrenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AtendimentoRoute: AtendimentoRoute,
  CausaAnimalRoute: CausaAnimalRoute,
  ComunidadeRoute: ComunidadeRoute,
  GestaoRoute: GestaoRoute,
  MedicamentosRoute: MedicamentosRoute,
  OcorrenciaRoute: OcorrenciaRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  SaudeRoute: SaudeRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
